openapi: 3.0.0
info:
  title: Shelly Gen 2 Device HTTP API
  version: 1.0.0
servers:
  - url: https://shelly-api-docs.shelly.cloud/gen2/
paths:
  # WiFi Methods
  /rpc/WiFi.GetConfig:
    get:
      tags:
        - Wifi Methods
      summary: Get Wifi Configuration
      description: Get the Wifi Configuration of the device. [Docs](https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/WiFi#wifigetstatus)
      responses:
        '200':
          description: Get Wifi Configuration response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WifiConfigResponse'
  /rpc/WiFi.GetStatus:
    get:
      tags:
        - Wifi Methods
      summary: Get Wifi Status
      description: Get the Wifi Status of the device. [Docs](https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/WiFi#wifigetconfig-example)
      responses:
        '200':
          description: Get Wifi Status response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WifiStatusResponse'
  /rpc/Wifi.ListAPClients:
    get:
      tags:
        - Wifi Methods
      summary: List WiFi AP Clients
      description: List WiFi AP Clients of the device. [Docs](https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/WiFi#wifilistapclients)
      responses:
        '200':
          description: WiFi List AP Clients response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WifiListAPClientsResponse'

components:
  schemas:
    # WiFi Methods
    # WiFi.GetStatus
    WifiStatusResponse:
      properties:
        id:
          type: number
        src:
          type: string
        dst:
          type: string
        result:
          $ref: '#/components/schemas/WifiStatus'
      required:
        - id
        - src
        - dst
        - result
      additionalProperties: false
      title: WifiStatusResponse
      example:
        {
          "id": 1,
          "src": "shellyblugw-a842e33f71f0",
          "dst": "my_self",
          "result": {
            "sta_ip": null,
            "status": "connecting",
            "ssid": null,
            "rssi": 0
          }
        }
    WifiStatus:
      properties:
        sta_ip:
          nullable: true
          type: string
        status:
          type: string
        ssid:
          nullable: true
          type: string
        rssi:
          type: number
        ap_client_count:
          type: number
      required:
        - sta_ip
        - status
        - ssid
        - rssi
        - ap_client_count
      additionalProperties: false
      title: WifiStatus
      type: object

    # WiFi.GetConfig
    WifiConfigResponse:
      properties:
        id:
          type: number
        src:
          type: string
        dst:
          type: string
        result:
          $ref: '#/components/schemas/WifiConfig'
      required:
        - id
        - src
        - dst
        - result
      additionalProperties: false
      title: WifiConfigResponse
      example:
        {
          "id": 1,
          "src": "shellyblugw-a842e33f71f0",
          "dst": "my_self",
          "result": {
            "ap": {
              "ssid": "ShellyBluGw-A842E33F71F0",
              "is_open": true,
              "enable": true,
              "range_extender": {
                "enable": false
              }
            },
            "sta": {
              "ssid": "HUAWEI-B315-9985",
              "is_open": false,
              "enable": true,
              "ipv4mode": "dhcp",
              "ip": null,
              "netmask": null,
              "gw": null,
              "nameserver": null
            },
            "sta1": {
              "ssid": "limao",
              "is_open": true,
              "enable": false,
              "ipv4mode": "dhcp",
              "ip": null,
              "netmask": null,
              "gw": null,
              "nameserver": null
            },
            "roam": {
              "rssi_thr": -80,
              "interval": 60
            }
          }
        }
    WifiConfig:
      properties:
        ap:
          $ref: '#/components/schemas/WifiAccessPoint'
        sta:
          $ref: '#/components/schemas/WifiStation'
        sta1:
          $ref: '#/components/schemas/WifiStation'
        roam:
          $ref: '#/components/schemas/WifiRoaming'
      required:
        - ap
        - sta
        - sta1
        - roam
      additionalProperties: false
      title: WifiConfig
      type: object
    WifiAccessPointWithPass:
      properties:
        pass:
          type: string
      required:
        - pass
      additionalProperties: false
      title: WifiAccessPointWithPass
      type: object
    WifiRoaming:
      properties:
        rssi_thr:
          type: number
        interval:
          type: number
      required:
        - rssi_thr
        - interval
      additionalProperties: false
      title: WifiRoaming
      type: object
    WifiStationWithPass:
      properties:
        ssid:
          nullable: true
          type: string
        is_open:
          type: boolean
        enable:
          type: boolean
        ipv4mode:
          enum:
            - dhcp
            - static
          type: string
        ip:
          type: string
        netmask:
          type: string
        gw:
          type: string
        nameserver:
          type: string
        pass:
          type: string
      required:
        - ssid
        - is_open
        - enable
        - ipv4mode
        - ip
        - netmask
        - gw
        - nameserver
        - pass
      additionalProperties: false
      title: WifiStationWithPass, WifiStation
      type: object
    WifiAccessPoint:
      properties:
        ssid:
          type: string
        is_open:
          type: boolean
        enable:
          type: boolean
        range_extender:
          type: object
          properties:
            enable:
              type: boolean
      required:
        - ssid
        - is_open
        - enable
        - range_extender
      additionalProperties: false
      title: WifiAccessPoint
      type: object
    WifiStation:
      properties:
        ssid:
          nullable: true
          type: string
        is_open:
          type: boolean
        enable:
          type: boolean
        ipv4mode:
          enum:
            - dhcp
            - static
          type: string
        ip:
          type: string
        netmask:
          type: string
        gw:
          type: string
        nameserver:
          type: string
      required:
        - ssid
        - is_open
        - enable
        - ipv4mode
        - ip
        - netmask
        - gw
        - nameserver
      additionalProperties: false
      title: WifiStation
      type: object

    # Wifi.ListAPClients
    WifiListAPClientsResponse:
      properties:
        id:
          type: number
        src:
          type: string
        dst:
          type: string
        result:
          $ref: '#/components/schemas/ListAPClients'
      required:
        - id
        - src
        - dst
        - result
      additionalProperties: false
      title: WifiListAPClientsResponse
    ListAPClients:
      properties:
        ts:
          nullable: true
          type: number
        ap_clients:
          items:
            $ref: '#/components/schemas/ApClient'
          type: array
      required:
        - ts
        - ap_clients
      additionalProperties: false
      title: ListAPClients
      type: object
    ApClient:
      properties:
        mac:
          type: string
        ip:
          type: string
        ip_static:
          type: boolean
        mport:
          type: number
        since:
          type: number
      required:
        - mac
        - ip
        - ip_static
        - mport
        - since
      additionalProperties: false
      title: ApClient
      type: object
